In [1]:
from PIL import Image 
import random
from numpy import array 
import numpy as np
img = Image.open('Lena.png')

ar = array(img)

In [2]:
print(ar)

[[160 160 160 ... 169 154 129]
 [161 160 159 ... 168 154 129]
 [160 161 160 ... 168 154 129]
 ...
 [ 50  49  55 ... 106 103 104]
 [ 49  50  58 ... 107 109 111]
 [ 50  49  59 ... 107 108 112]]


In [19]:
new = np.zeros((4,4))
for i in range(0,len(ar),4):
    for j in range(0,len(ar[i]),4):
        m,n=0,0
        p,q=i,j
        while p <=i+4:
            while q  <=j+4:
                new[m][n] = ar[p][q]
                n=+1
                q+=1
            m=+1
            p=+1
            n=0
            q=j
        print("Printing {}{}".format(i,j))
        shuffeled_image3 = Image.fromarray(new)
        shuffeled_image3.save("./pics/p{}{}.png".format(i,j))
        


KeyboardInterrupt: 